THE UK is facing a future construction crisis because of a failure to plant trees to produce wood, a trade body has warned.
      Confor chiefs believe urgent action is needed to reduce the country's reliance on timber imports and provide a stable supply of wood for future generations.
      Currently only 20 per cent of the UK's wood requirement is homegrown while it remains the second-largest net importer of timber in the world, bringing in around £7.5 billion annually.
      Coming at a time of fresh incentives from the UK government for landowners to grow more trees, the trade body says these don't go far enough and fail to promote the benefits of planting them to boost timber supplies.
      “Not only are we facing a carbon crisis now, but we will also be facing a future construction crisis because of a failure to plant trees to produce wood," said Stuart Goodall, chief executive of Confor. "For decades we have not taken responsibility for investing in our domestic wood supply, leaving us exposed to fluctuating prices and fighting for future supplies of wood as global demand rises and our own supplies fall."
      The UK has ideal conditions for growing wood to build low-carbon homes and is a global leader in certifying that its forests are sustainably managed, Confor say. While around three quarters of Scottish homes are built from Scottish timber, the use of home-grown wood in England is only around 25 per cent.
      The causes of the UK’s current position are complex and range from outdated perceptions of productive forestry to the decimation of trees from grey squirrels. It also encompasses significant hesitation on behalf of farmers and other landowners to invest in longer term planting projects.
      While productive tree planting can deliver real financial benefits to rural economies and contribute to the UK’s net zero strategy, the focus of government support continues to be on food production and the rewilding and planting of native woodland solely for biodiversity.
      The recently launched Woodland Creation Offer, which pledges farmers and landowners £10,000 for each hectare planted, failed to mention timber production, albeit the Forestry Commission's Richard Stanford has since spoken of the importance of it.
      Stuart added: "While food production and biodiversity health are clearly of critical importance, we need our land to also provide secure supplies of wood for construction, manufacturing and to contribute to net zero.
      “While the UK government has stated its ambition for more tree planting, there has been little action on the ground. Confor is now calling for much greater impetus behind those aspirations to ensure we have enough wood to meet increasing demand.”



Your social life is defined as "the activities you do with other people, for pleasure, when you are not working". It's important to have a social life, but what's right for one person won’t be right for another. Some of us feel energised by spending lots of time with others, （ 1  ） some of us may feel drained, even if it’s doing something we enjoy.

This is why finding a （  2  ） in your social life is key. Spending too much time on your own, not （  3  ） others, can make you feel lonely and （  4  ）. Loneliness is known to impact on your mental health and （  5  ） a low mood. Anyone can feel lonely at any time. This might be especially true if, （  6  ） you are working from home and you are （  7  ）on the social conversations that happen in the office. Other life changes also （  8  ） periods of loneliness too, such as retirement, changing a job or becoming a parent.

It’s important to recognize feelings or loneliness. There are ways to （  9  ） a social life. But it be overwhelming （  10  ）. You can then find groups and activities related to those where you will be able to meet （  11  ） people. There are groups aimed at new parents, at those who want to （  12  ） a new sport for the first time or networking events for those in the same profession to meet up and （  13  ） ideas.

On the other hand, it is （  14  ）possible to have too much of a social life. If you feel like you’re always doing something and there is never any （  15  ） in your calendar for downtime, you could suffer social burnout or social （  16  ）. We all have our own social limit and it's important to recognize when you're feeling like it's all too much. Low mood, low energy, irritability and trouble sleeping could all be （  17  ） of poor social health. Make sure you （  18  ） some time in your diary when you're  （  19  ） for socialising and use this time to relax, （  20  ） and recover.


Anger over AI’s role in exacerbating inequality could endanger the technology’s future. In her new book Cogs and Monsters: What Economics Is, and What It Should Be, Diane Coyle, an economist at Cambridge University, argues that the digital economy requires new ways of thinking about progress. “Whatever we mean by the economy growing, by things getting better, the gains will have to be more evenly shared than in the recent past,” she writes. “An economy of tech millionaires or billionaires and gig workers, with middle-income jobs undercut by automation, will not be politically sustainable.”
      Improving living standards and increasing prosperity for more people will require greater use of digital technologies to boost productivity in various sectors, including health care and construction, says Coyle. But people can’t be expected to embrace the changes if they’re not seeing the benefits—if they’re just seeing good jobs being destroyed.
      In a recent interview with MIT Technology Review, Coyle said she fears that tech’s inequality problem could be a roadblock to deploying AI. “We’re talking about disruption,” she says. “These are transformative technologies that change the ways we spend our time every day, that change business models that succeed.” To make such “tremendous changes,” she adds, “you need social buy-in.”
      Instead, says Coyle, resentment is simmering among many as the benefits are perceived to go to elites in a handful of prosperous cities.
      In the US, for instance, during much of the 20th century the various regions of the country were—in the language of economists—“converging,” and financial disparities decreased. Then, in the 1980s, came the onslaught of digital technologies, and the trend reversed itself. Automation wiped out many manufacturing and retail jobs. New, well-paying tech jobs were clustered in a few cities.
      The dominance of a few cities in the invention and commercialization of AI means that geographical disparities in wealth will continue to soar. Not only will this foster political and social unrest, but it could, as Coyle suggests, hold back the sorts of AI technologies needed for regional economies to grow.
      Part of the solution could lie in somehow loosening the stranglehold that Big Tech has on defining the AI agenda. That will likely take increased federal funding for research independent of the tech giants. Muro and others have suggested hefty federal funding to help create US regional innovation centers, for example.


One of the biggest challenges in keeping unsafe aging drivers off the road is convincing them that it’s time to turn over the keys.
“It’s a complete life-changer” when someone stops — or is forced to stop — driving, said Anne M. Menke, a former risk manager for the Ophthalmic Mutual Insurance Co.
Part of the problem in keeping older drivers safe is that the difficulties are addressed piecemeal by different professions with different focuses, including gerontologists, highway administration officials, automotive engineers and others, said Elizabeth Dugan, an associate professor of gerontology at the University of Massachusetts. “There’s not a National Institute of Older Driver Studies,” she said. “We need better evidence on what makes drivers unsafe” and what can help, said Dugan, who has written extensively about healthy aging for Consumer Reports and other organizations.
One thing that does seem to work is requiring drivers to report in person for license renewal. Mandatory in-person renewal was associated with a 31 percent reduction in fatal crashes involving drivers 85 or older, according to one study. Passing vision tests also produced a similar decline in fatal crashes for those drivers, although there appeared to be no benefit from combining the two.
Many older drivers don’t see eye doctors or can’t afford to. Primary care providers have their hands full and may not be able to follow through with patients who have trouble driving because they can’t turn their heads or remember where they are going — or have gotten shorter and haven’t changed their seat settings sufficiently to reach car pedals easily.
As long as there are other cars on the roads, self-driving cars won’t solve the problems of crashes, said Dugan. Avoiding dangers posed by all those human drivers would require too many algorithms, she said. But we need to do more to improve safety, said Dugan.
“If we’re going to have 100-year lives, we need cars that a 90-year-old can drive comfortably.”



If you look at the apps on your phone, chances are you have at least one related to your health—and probably several. Whether it is a mental health app, a fitness tracker, a connected health device or something else, many of us are taking advantage of this technology to keep better track of our health in some shape or form. Recent research from the Organization for the Review of Care and Health Applications found that 350,000 health apps were available on the market, 90,000 of which launched in 2020 alone.
While these apps have a great deal to offer, it is not always clear how the personal information we input is collected, safeguarded and shared online. Existing health privacy law, such as the Health Insurance Portability and Accountability Act, is primarily focused on the way hospitals, doctors’ offices, clinics and insurance companies store health records online. The health information these apps and health data tracking wearables are collecting typically does not receive the same legal protections.
Without additional protections in place, companies may share (and potentially monetize) personal health information in a way consumers may not have authorized or anticipated. In 2021, Flo Health faced a Federal Trade Commission（FTC） investigation. The FTC alleged in a complaint that "despite express privacy claims, the company took control of users' sensitivity fertility data and shared it with third parties.” Flo Health and the FTC settled the matter with a Consent Order requiring the company to get app users' express affirmative consent before sharing their health information as well as to instruct the third parties to delete the data they had obtained.
Section 5 of the FTC Act empowers the FTC to initiate enforcement action against unfair or deceptive acts, meaning the FTC can only act after the fact if a company's privacy practices are misleading or cause unjustified consumer harm. While the FTC is doing what it can to ensure apps are keeping their promises to consumers around the handling of their sensitive health information, the rate at which these health apps are hitting the market demonstrates just how immense of a challenge this is.
As to the prospects for federal legislation, commentators suggest that comprehensive federal privacy legislation seems unlikely in the short term. States have begun implementing their own solutions to shore up protections for consumer-generated health data. California has been at the forefront of state privacy efforts with the California Consumer Privacy Act of 2018. Virginia，Colorado and Utah have also recently passed state consumer data privacy legislation.




High school students eager to stand out in the college application process often participate in a litany of extracurricular activities hoping to bolster their chances of admission a selective undergraduate institution.
However, college admissions experts say that the quality of a college hopeful's extracurricular activities matter more than the number of activities he or she participates in.
Sue Rexford, the director of college guidance at the Charles. E. Smith Jewish Day School , says it is not necessary for a student,filling out the Common Application to list lo activities in the application.
"No college will expect that a students has a huge laundry list of extracurriculars that they have been passionately involved in each for an tended period of time, " Rexford wrote in an email.
Experts say it is tougher to distinguish oneself in a school-affiliated extracurricular activity that is common among high school students than it is to stand out while doing an uncommon activity.
"The competition to stand out and make an impact is going to be much stiffer, and so if they 're going to do a popular activity, I'd say, be the best at it."says Sara Harherson, a college admission consultant.
High school students who have an impressive personal project they are working on independently often impress colleges, experts say.
"For example, a student with an interest in entrepreneurship could demonstrate skills and potential by starting a profitable small business." Olivia Valdes, the founder or Zen Admissions consulting firm, wrote in an email.
Josoph Adegboyega—Edun, a Maryland High school guidance counselor, says unconventional extracurricular activities can help students impress college admissions offices, assuming they demonstrated serious commitment."Again, since one of the big question high school seniors must consider is 'What makes you unique?', having an uncommon extracurricular activity vs. a conventional one is an advantage," he wrote in an email.
Experts say demonstrating talent in at least one extracurricular activity can help in the college admissions process, especially at top-tier undergraduate institutions.
“Distinguishing yourself in one focused type of extracurricular activity can be a positive in the admissions process, especially for highly selective institutions, where having top grades and test scores is not enough,”Katie Kelley admissions counselor at Ivy Wise admissions consultancy, wrote in an email. "Students need to have that quality or hook that will appeal to admissions officers and allow them to visualize how the student might come and enrich their campus community.”
Extracurricular activities related to the college major declared on a college application are beneficial, experts suggest. "If you already know your major, having an extracurricular that fits into that major can be a big plus," says Mayghin Levine, the manager of educational opportunities with The Cabbage Patch Settlement House, a Louisville, Kentucky, nonprofit community center.
High school students who have had a strong positive influence on their community through an extracurricular activity may impress a college and win a scholarship, says Erica Gwyn, a former math and science magnet program assistant at a public high school who is now executive director of the Kaleidoscope Careers Academy in Atlanta, a nonprofit organization.



 With the smell of coffee and fresh bread floating in the air, stalls bursting with colorful vegetables and tempting cheeses, and the buzz of friendly chats, farmers’ markets are a feast for the senses. They also provide an opportunity to talk to the people responsible for growing or raising your food, support your local economy and pick up fresh seasonal produce—all at the same time.
      Farmers’ markets are usually weekly or monthly events, most often with outdoor stalls, which allow farmers or producers to sell their food directly to customers. The size or regularity of markets can vary from season to season, depending on the area’s agricultural calendar, and you’re likely to find different produce on sale at different times of the year. By cutting out the middlemen, the farmers secure more profit for their produce. Shoppers also benefit from seeing exactly where—and to who—their money is going.


THE UK is facing a future construction crisis because of a failure to plant trees to produce wood, a trade body has warned.
英国一家贸易机构警告称，由于未能种植树木以生产木材，英国正面临未来的建筑危机。
Confor chiefs believe urgent action is needed to reduce the country's reliance on timber imports and provide a stable supply of wood for future generations.
英国森林与木材协会（Confor）的负责人认为，需要采取紧急行动来减少该国对木材进口的依赖，并为后代提供稳定的木材供应。
Currently only 20 per cent of the UK's wood requirement is homegrown while it remains the second-largest net importer of timber in the world, bringing in around £7.5 billion annually.
目前，英国木材需求中只有 20% 是本土生产的，而英国仍然是世界上第二大木材净进口国，每年进口约 75 亿英镑。
Coming at a time of fresh incentives from the UK government for landowners to grow more trees, the trade body says these don't go far enough and fail to promote the benefits of planting them to boost timber supplies.
在英国政府为土地所有者提供新的激励措施以种植更多树木之际，该贸易机构表示，这些措施还不够，未能宣传种植树木以增加木材供应的好处。
“Not only are we facing a carbon crisis now, but we will also be facing a future construction crisis because of a failure to plant trees to produce wood,"said Stuart Goodall, chief executive of Confor."For decades we have not taken responsibility for investing in our domestic wood supply, leaving us exposed to fluctuating prices and fighting for future supplies of wood as global demand rises and our own supplies fall."
英国森林与木材协会首席执行官斯图尔特・古多尔（Stuart Goodall）表示：“我们现在不仅面临着碳危机，而且由于未能种植树木以生产木材，我们还将面临未来的建筑危机。几十年来，我们一直没有为投资国内木材供应承担责任，这使得我们面临价格波动的风险，并且随着全球需求的增加和我们自己的供应下降，我们不得不为未来的木材供应而努力。”
The UK has ideal conditions for growing wood to build low-carbon homes and is a global leader in certifying that its forests are sustainably managed, Confor say. While around three quarters of Scottish homes are built from Scottish timber, the use of home-grown wood in England is only around 25 per cent.
英国森林与木材协会表示，英国拥有种植木材以建造低碳住宅的理想条件，并且在认证其森林得到可持续管理方面处于全球领先地位。虽然大约四分之三的苏格兰房屋是用苏格兰木材建造的，但在英格兰，本土木材的使用量仅约为 25%。
The causes of the UK’s current position are complex and range from outdated perceptions of productive forestry to the decimation of trees from grey squirrels. It also encompasses significant hesitation on behalf of farmers and other landowners to invest in longer term planting projects.
英国目前状况的原因很复杂，从对生产性林业的过时观念到灰松鼠对树木的大量破坏。这也包括农民和其他土地所有者在投资长期种植项目方面的重大犹豫。
While productive tree planting can deliver real financial benefits to rural economies and contribute to the UK’s net zero strategy, the focus of government support continues to be on food production and the rewilding and planting of native woodland solely for biodiversity.
虽然富有成效的植树可以为农村经济带来真正的经济效益，并为英国的净零战略做出贡献，但政府支持的重点仍然是粮食生产以及仅为生物多样性而进行的野化和本土林地种植。
The recently launched Woodland Creation Offer, which pledges farmers and landowners £10,000 for each hectare planted, failed to mention timber production, albeit the Forestry Commission's Richard Stanford has since spoken of the importance of it.
最近推出的林地创建计划承诺为农民和土地所有者每种植一公顷土地提供 10000 英镑，但没有提到木材生产，尽管林业委员会的理查德・斯坦福（Richard Stanford）此后谈到了木材生产的重要性。
Stuart added: "While food production and biodiversity health are clearly of critical importance, we need our land to also provide secure supplies of wood for construction, manufacturing and to contribute to net zero.
斯图尔特补充说：“虽然粮食生产和生物多样性健康显然至关重要，但我们也需要我们的土地为建筑、制造业提供安全的木材供应，并为实现净零做出贡献。”
“While the UK government has stated its ambition for more tree planting, there has been little action on the ground. Confor is now calling for much greater impetus behind those aspirations to ensure we have enough wood to meet increasing demand.”
“虽然英国政府已经表明了其增加植树的雄心，但在实际行动方面却很少。英国森林与木材协会现在呼吁在这些愿望背后给予更大的推动力，以确保我们有足够的木材来满足不断增长的需求。




